# Generated by Django 5.0 on 2023-12-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0003_product_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
